POST  http://localhost:3001/api/signup
Content-Type: application/json

{
  "username": "Admin",
  "firstName": "Tyler",
  "lastName": "VanSickle",
  "email": "admin@test.com",
  "birthday": "1999-10-06",
  "password": "Admin",
  "isAdmin": true
}

###
// When using this login, you only need to provide the username and password
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "Admin",
  "password": "Admin"
}

###

POST http://localhost:3001/api/courses/2/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0LCJpYXQiOjE3NDU1MDczMTEsImV4cCI6MTc0NTUxMDkxMX0.24khAbTnwFjX_jp71gx09nnxz3lme5dsowqJb6KEeZM

{
  "username": "Admin"
}

###

GET http://localhost:3001/api/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0LCJpYXQiOjE3NDU1MDczMTEsImV4cCI6MTc0NTUxMDkxMX0.24khAbTnwFjX_jp71gx09nnxz3lme5dsowqJb6KEeZM

###

GET http://localhost:3001/api/allcourses
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo4LCJpYXQiOjE3NDQ3MjQ0MzMsImV4cCI6MTc0NDcyODAzM30.HK3z1JNGPa8AKjgheaV3CMyLQqE-gk0_gOzBuQqIQho
=======
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0LCJpYXQiOjE3NDQ2NDE3MjksImV4cCI6MTc0NDY0NTMyOX0.Nn02M8m4AOAjE8MGWmlFGpgYA_trpv__1955YiABslE

###
// This is the endpoint to get all students
GET http://localhost:3001/admin/students
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0LCJpYXQiOjE3NDU1MTAyOTUsImV4cCI6MTc0NTUxMzg5NX0.DXfLy4r-fYukjoFmhKDFQGKZEj30SpIMBBLcmKfUTEo

### 

GET http://localhost:3001/api/courses
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMCwiaWF0IjoxNzQ1MTU2OTQ4LCJleHAiOjE3NDUxNjA1NDh9.dhl7bS8tPjyYRzCfOygamFFu7OoBBrNm1HPof2z_dmU