POST  http://localhost:3001/api/signup
Content-Type: application/json

{
  "username": "BubbleV",
  "firstName": "Tyler",
  "lastName": "VanSickle",
  "email": "BubbleV@test.com",
  "birthday": "1999-10-06",
  "password": "Pass",
  "isAdmin": true
}

###
// When using this login, you only need to provide the username and password
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "Bubbles",
  "password": "Pass"
}

###

POST http://localhost:3001/api/courses/1/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJpYXQiOjE3NDQyMDYwNTIsImV4cCI6MTc0NDIwOTY1Mn0.hz_ktKnOn5Y_aQzqRaIR2QhcVvp1uRjcqMAeYwa0s8M

{
  "username": "Bubbles"
}

###

GET http://localhost:3001/api/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJpYXQiOjE3NDQwNDk0OTUsImV4cCI6MTc0NDA1MzA5NX0.QRw72zPn54Jao8ivsfGCAqjoChkCZ4pWxHKkhXxJs7Y