POST  http://localhost:3001/api/signup
Content-Type: application/json

{
  "username": "Admin",
  "firstName": "Tyler",
  "lastName": "VanSickle",
  "email": "admin@test.com",
  "birthday": "1999-10-06",
  "password": "Admin",
  "isAdmin": true
}

###
// When using this login, you only need to provide the username and password
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "Adamino",
  "password": "pass"
}

###

POST http://localhost:3001/api/courses/2/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMCwiaWF0IjoxNzQ1NDE1NTQ3LCJleHAiOjE3NDU0MTkxNDd9.N-oXHh6Gf7ORim5whAYGittWNPVqL4k53GOkTAZCNQk

{
  "username": "Admin"
}

###

GET http://localhost:3001/api/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo4LCJpYXQiOjE3NDQ3MjQ0MzMsImV4cCI6MTc0NDcyODAzM30.HK3z1JNGPa8AKjgheaV3CMyLQqE-gk0_gOzBuQqIQho

###

GET http://localhost:3001/api/allcourses
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo4LCJpYXQiOjE3NDQ3MjQ0MzMsImV4cCI6MTc0NDcyODAzM30.HK3z1JNGPa8AKjgheaV3CMyLQqE-gk0_gOzBuQqIQho
=======
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0LCJpYXQiOjE3NDQ2NDE3MjksImV4cCI6MTc0NDY0NTMyOX0.Nn02M8m4AOAjE8MGWmlFGpgYA_trpv__1955YiABslE

###
// This is the endpoint to get all students
GET http://localhost:3001/admin/students
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo5LCJpYXQiOjE3NDU0MzM4MzYsImV4cCI6MTc0NTQzNzQzNn0.YG3X8xwZ7Fkle-PNcieP_v0U5_km-ul9a7luwqkV218

### 

GET http://localhost:3001/api/courses
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo5LCJpYXQiOjE3NDU1ODg3NjYsImV4cCI6MTc0NTU5MjM2Nn0.KiPV7V0cH4wnvEp5A-bukjV62SGcD6eRKb49orSpLhU

{
  "user_id" : 10
}
